### ISSUE TITLE
Create IMPRESS env on Delta (NCSA)

### ISSUE THREAD

**Issue by mtitov** [radical-collaboration/IMPRESS#12]
Build conda env and test corresponding packages individually
- [ ] PyRosetta
- [x] mpnn (@JonathanEAsh will provide instructions)

**Comment by mturilli** [comment]
Document the process and create a dependencies file for RCT. Add this to RP documentation if needed.

**Comment by mtitov** [comment]
@JonathanEAsh can you please provide (1) test example for PyRosseta, and (2) instructions for ProteinMPNN installation and its corresponding test example.

Related PR https://github.com/radical-collaboration/IMPRESS/pull/14

**Comment by JonathanEAsh** [comment]
1 - For pyrosetta, I would recommend simply loading a pose and trying to relax it. Make sure you have joey_utils in your working directory.
from pyrosetta import *
init()
from joey_utils import fast_relax_mover
pose=pose_from_pdb("FILEPATH")
fr=fast_relax_mover()
fr.apply(pose)
pose.dump_pdb("OUTPATH")
2 - For ProteinMPNN, please follow the instructions here for the environment: https://github.com/dauparas/ProteinMPNN
They also have some test examples, with all of the requisite input files already included. Simply run one of those to verify everything is working
